Repository GSG-G11/shoestore, pull requests merged in 2022-04, with the labels that each got.

#2 00 add file structure
  .eslintrc.json
  .vscode/setting.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  config.env
  package-lock.json
  package.json
  server/app.js
  server/controller/index.js
  server/database/config/build.sql
  server/database/queries/index.js
  server/index.js
  server/router/index.js
Labels: Done

#4 create database
  client/package-lock.json
  package-lock.json
  server/database/build/build.js
  server/database/build/build.sql
  server/database/build/commandBuild.js
  server/database/config/build.sql
  server/database/config/connection.js
Labels: Awaiting Review, Done

#6 add structure of react routes
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/App.jsx
  client/src/App.test.js
  client/src/index.js
  client/src/index.jsx
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
Labels: Awaiting Review

#12 10 create router
  .gitignore
  client/package-lock.json
  client/src/App.jsx
  client/src/components/Ad/Ad.jsx
  client/src/components/Ad/ad.css
  client/src/components/Home/background.png
  client/src/components/Home/home.css
  client/src/components/Home/home.jsx
  config.env
  server/app.js
  server/controller/addProduct.js
  server/controller/deleteProduct.js
  server/controller/getProducts.js
  server/controller/index.js
  server/controller/updateProduct.js
  server/database/config/connection.js
  server/database/queries/addProductDB.js
  server/database/queries/deleteProductDB.js
  server/database/queries/getProductsDB.js
  server/database/queries/index.js
  server/database/queries/updateProductDB.js
  server/router/index.js
Labels: Approved

#11 Create-Home #8
  client/package-lock.json
  client/src/App.jsx
  client/src/components/Ad/Ad.jsx
  client/src/components/Ad/ad.css
  client/src/components/Home/background.png
  client/src/components/Home/home.css
  client/src/components/Home/home.jsx
Labels: Awaiting Review

#16 15 edit db
  server/app.js
  server/controller/addProduct.js
  server/controller/deleteProduct.js
  server/controller/getProducts.js
  server/controller/updateProduct.js
  server/database/build/build.sql
  server/database/config/connection.js
  server/database/queries/addProduct.js
  server/database/queries/addProductDB.js
  server/database/queries/deleteProduct.js
  server/database/queries/deleteProductDB.js
  server/database/queries/getProducts.js
  server/database/queries/getProductsDB.js
  server/database/queries/index.js
  server/database/queries/updateProduct.js
  server/database/queries/updateProductDB.js
  server/router/index.js
Labels: Approved

#14 creating header
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/compnents/header/downHeader/Dropdown.jsx
  client/src/compnents/header/downHeader/NavigationMenu.jsx
  client/src/compnents/header/downHeader/downHeader.css
  client/src/compnents/header/upperHeader/CartIcon.jsx
  client/src/compnents/header/upperHeader/LoginButton.jsx
  client/src/compnents/header/upperHeader/Logo.jsx
  client/src/compnents/header/upperHeader/SearchBar.jsx
  client/src/compnents/header/upperHeader/upperHeader.css
  client/src/compnents/images/running-shoes.png
Labels: Awaiting Review

#21 solve conflicts
  server/controller/addProduct.js
  server/controller/deleteProduct.js
  server/controller/getProducts.js
  server/controller/updateProduct.js
Labels: Awaiting Review

#24 update the footer
  client/src/App.css
  client/src/App.jsx
  client/src/components/Footer/FooterLeft/FooterLeft.css
  client/src/components/Footer/FooterLeft/FooterLeft.jsx
  client/src/components/Footer/FooterRight/FooterRight.css
  client/src/components/Footer/FooterRight/FooterRight.jsx
  client/src/components/UlCompnents/Ul.css
  client/src/components/UlCompnents/Ul.jsx
Labels: Awaiting Review

#26 add the product components
  client/package-lock.json
  client/package.json
  client/src/components/Product/ProductCard.jsx
  client/src/components/Product/style.css
Labels: Awaiting Review

#31 28 create product page
  client/src/App.jsx
  client/src/components/Product/Product.jsx
  client/src/components/Product/product.css
  server/database/config/connection.js
Labels: Approved

#32 create cart component
  client/src/App.jsx
  client/src/components/Cart/Cart.css
  client/src/components/Cart/Cart.jsx
  client/src/components/Cart/Screenshot from 2022-04-11 16-25-35.png
Labels: Approved

#37 handle cart products
  client/package-lock.json
  client/src/components/Cart/Cart.css
  client/src/components/Cart/Cart.jsx
  server/database/build/build.sql
Labels: Approved

#40 style home
  client/package.json
  client/src/components/Product/ProductCard.jsx
  client/src/components/header/upperHeader/CartIcon.jsx
  client/src/pages/home/Top/style.scss
  client/src/pages/home/displayProducts/Products.jsx
  client/src/pages/home/displayProducts/style.css
  client/src/pages/home/index.jsx
  package-lock.json
  server/app.js
  server/database/config/connection.js
Labels: Awaiting Review

#42 attach cart to home
  client/src/App.jsx
  client/src/components/Product/ProductCard.jsx
  client/src/components/header/index.jsx
  client/src/components/header/upperHeader/CartIcon.jsx
  client/src/pages/Cart/Cart.css
  client/src/pages/Cart/Cart.jsx
  client/src/pages/Cart/Screenshot from 2022-04-11 16-25-35.png
  client/src/pages/home/displayProducts/Products.jsx
  client/src/pages/home/index.jsx
Labels: Awaiting Review

#36 Create Seller Page #35
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.jsx
  client/src/components/Footer/CombinedFooter.css
  client/src/components/Footer/CombinedFooter.jsx
  client/src/components/Modal/Modal.jsx
  client/src/components/Modal/style.scss
  client/src/components/Product/ProductCard.jsx
  client/src/components/Product/style.css
  client/src/components/UlCompnents/Ul.jsx
  client/src/components/header/downHeader/downHeader.css
  client/src/components/header/upperHeader/upperHeader.css
  client/src/pages/home/index.jsx
  client/src/pages/seller/index.jsx
  client/src/pages/seller/seller.css
Labels: Approved

#46 Update Server
  client/package-lock.json
  server/controller/addProduct.js
  server/controller/getProductID.js
  server/controller/index.js
  server/controller/updateProduct.js
  server/database/queries/getProductByID.js
  server/database/queries/index.js
  server/database/queries/updateProduct.js
  server/router/index.js
Labels: Approved

#48 local storage in loing page
  client/src/App.jsx
  client/src/components/Login/LoginForm.css
  client/src/components/Login/LoginForm.jsx
Labels: In Progress

#45 final product of home page
  client/src/App.jsx
  client/src/components/Product/ProductCard.jsx
  client/src/components/header/downHeader/Dropdown.jsx
  client/src/pages/home/Top/TopFilter.jsx
  client/src/pages/home/displayProducts/Products.jsx
  client/src/pages/home/index.jsx
  client/src/pages/seller/index.jsx
  server/database/build/build.sql
Labels: Approved

#52 finish of product details
  client/src/App.jsx
  client/src/components/Product/Product.jsx
  client/src/components/Product/ProductCard.jsx
  client/src/pages/Cart/Cart.jsx
  client/src/pages/productDetails/ProductDet.jsx
  client/src/pages/productDetails/product.css
Labels: Awaiting Review

#51 Handle Delete Product & Update category#50
  client/src/App.css
  client/src/components/Modal/Modal.jsx
  client/src/components/Modal/style.scss
  client/src/components/Product/ProductCard.jsx
  client/src/components/Product/style.css
  client/src/components/header/index.jsx
  client/src/components/header/upperHeader/upperHeader.css
  client/src/pages/Cart/Cart.css
  client/src/pages/Cart/Cart.jsx
  client/src/pages/home/displayProducts/Products.jsx
  client/src/pages/seller/index.jsx
  client/src/pages/seller/seller.css
  server/controller/updateProduct.js
  server/database/build/build.sql
  server/database/queries/addProduct.js
  server/database/queries/updateProduct.js
Labels: Awaiting Review

#53 Handled login form, style and Login/Logout buttons
  client/public/index.html
  client/src/App.jsx
  client/src/components/Login/LoginForm.css
  client/src/components/Login/LoginForm.jsx
  client/src/components/Modal/Modal.jsx
  client/src/components/Product/ProductCard.jsx
  client/src/components/Product/style.css
  client/src/components/header/index.jsx
  client/src/components/header/upperHeader/LoginButton.jsx
  client/src/components/header/upperHeader/upperHeader.css
  client/src/pages/Text.jsx
  package-lock.json
Labels: Awaiting Review

#54 create not found page
  client/src/App.jsx
  client/src/components/NotFound/NotFound.css
  client/src/components/NotFound/NotFound.jsx
  client/src/components/NotFound/Screenshot from 2022-04-14 03-45-07.png
Labels: Approved

#60 59 update readme
  README.md
  client/src/components/NotFound/NotFound.css
  client/src/components/NotFound/NotFound.jsx
  client/src/components/NotFound/Screenshot from 2022-04-14 03-45-07.png
  client/src/components/header/upperHeader/Logo.jsx
  server/database/build/build.sql
Labels: Approved

#61 Update #59
  client/src/components/Home/home.jsx
  client/src/components/Product/style.css
Labels: Awaiting Review
